# Generated by Django 4.2.5 on 2023-10-02 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_encoding_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name=''),
        ),
    ]
