# Generated by Django 4.2.5 on 2023-10-29 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_encoding_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='encoded_file',
            field=models.FileField(null=True, upload_to='encoded/'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name=''),
        ),
    ]
