# Generated by Django 4.2.5 on 2023-11-30 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_encoding_encoded_file_alter_encoding_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='frame_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name=''),
        ),
    ]
