# Generated by Django 4.2.5 on 2023-12-17 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_encoding_frame_number_alter_encoding_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4'])], verbose_name='')),
                ('secret_key', models.CharField(blank=True, max_length=80, null=True)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='encoding',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4'])], verbose_name=''),
        ),
    ]
